<?xml version="1.0" encoding="utf-8"?><Database Name="locationawarepm_db" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=q0qcqraoho.database.windows.net;Initial Catalog=locationawarepm_db;User ID=locationawarepm;Connect Timeout=60" SettingsObjectName="DroidPMClient.Properties.Settings" SettingsPropertyName="locationawarepm_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="locationawarepm.CommandItem" Member="CommandItems">
    <Type Name="CommandItem">
      <Column Name="id" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[__createdAt]" Member="__createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="[__updatedAt]" Member="__updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="[__version]" Member="__version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="command" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="workgoup" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="workgoup_state" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="auth_level" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="computername" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="terminateprocess" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>