#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroidPMClient
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="locationawarepm_db")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBlobBlob(BlobBlob instance);
    partial void UpdateBlobBlob(BlobBlob instance);
    partial void DeleteBlobBlob(BlobBlob instance);
    partial void InsertBlobContainer(BlobContainer instance);
    partial void UpdateBlobContainer(BlobContainer instance);
    partial void DeleteBlobContainer(BlobContainer instance);
    partial void InsertBookingItem(BookingItem instance);
    partial void UpdateBookingItem(BookingItem instance);
    partial void DeleteBookingItem(BookingItem instance);
    partial void InsertCommandItem(CommandItem instance);
    partial void UpdateCommandItem(CommandItem instance);
    partial void DeleteCommandItem(CommandItem instance);
    partial void InsertRegistration(Registration instance);
    partial void UpdateRegistration(Registration instance);
    partial void DeleteRegistration(Registration instance);
    partial void InsertShuttleService(ShuttleService instance);
    partial void UpdateShuttleService(ShuttleService instance);
    partial void DeleteShuttleService(ShuttleService instance);
    partial void InsertTodoItem(TodoItem instance);
    partial void UpdateTodoItem(TodoItem instance);
    partial void DeleteTodoItem(TodoItem instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertUserRegistration(UserRegistration instance);
    partial void UpdateUserRegistration(UserRegistration instance);
    partial void DeleteUserRegistration(UserRegistration instance);
    partial void InsertTable(Table instance);
    partial void UpdateTable(Table instance);
    partial void DeleteTable(Table instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::DroidPMClient.Properties.Settings.Default.locationawarepm_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BlobBlob> BlobBlobs
		{
			get
			{
				return this.GetTable<BlobBlob>();
			}
		}
		
		public System.Data.Linq.Table<BlobContainer> BlobContainers
		{
			get
			{
				return this.GetTable<BlobContainer>();
			}
		}
		
		public System.Data.Linq.Table<BookingItem> BookingItems
		{
			get
			{
				return this.GetTable<BookingItem>();
			}
		}
		
		public System.Data.Linq.Table<CommandItem> CommandItems
		{
			get
			{
				return this.GetTable<CommandItem>();
			}
		}
		
		public System.Data.Linq.Table<Registration> Registrations
		{
			get
			{
				return this.GetTable<Registration>();
			}
		}
		
		public System.Data.Linq.Table<ShuttleService> ShuttleServices
		{
			get
			{
				return this.GetTable<ShuttleService>();
			}
		}
		
		public System.Data.Linq.Table<TodoItem> TodoItems
		{
			get
			{
				return this.GetTable<TodoItem>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<UserRegistration> UserRegistrations
		{
			get
			{
				return this.GetTable<UserRegistration>();
			}
		}
		
		public System.Data.Linq.Table<Table> Tables
		{
			get
			{
				return this.GetTable<Table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.BlobBlobs")]
	public partial class BlobBlob : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTimeOffset ___createdAt;
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		
		private System.Data.Linq.Binary ___version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void On__createdAtChanging(System.DateTimeOffset value);
    partial void On__createdAtChanged();
    partial void On__updatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void On__updatedAtChanged();
    partial void On__versionChanging(System.Data.Linq.Binary value);
    partial void On__versionChanged();
    #endregion
		
		public BlobBlob()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__createdAt]", Storage="___createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset @__createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				if ((this.___createdAt != value))
				{
					this.On__createdAtChanging(value);
					this.SendPropertyChanging();
					this.___createdAt = value;
					this.SendPropertyChanged("__createdAt");
					this.On__createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__updatedAt]", Storage="___updatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> @__updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				if ((this.___updatedAt != value))
				{
					this.On__updatedAtChanging(value);
					this.SendPropertyChanging();
					this.___updatedAt = value;
					this.SendPropertyChanged("__updatedAt");
					this.On__updatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__version]", Storage="___version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary @__version
		{
			get
			{
				return this.___version;
			}
			set
			{
				if ((this.___version != value))
				{
					this.On__versionChanging(value);
					this.SendPropertyChanging();
					this.___version = value;
					this.SendPropertyChanged("__version");
					this.On__versionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.BlobContainers")]
	public partial class BlobContainer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTimeOffset ___createdAt;
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		
		private System.Data.Linq.Binary ___version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void On__createdAtChanging(System.DateTimeOffset value);
    partial void On__createdAtChanged();
    partial void On__updatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void On__updatedAtChanged();
    partial void On__versionChanging(System.Data.Linq.Binary value);
    partial void On__versionChanged();
    #endregion
		
		public BlobContainer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__createdAt]", Storage="___createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset @__createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				if ((this.___createdAt != value))
				{
					this.On__createdAtChanging(value);
					this.SendPropertyChanging();
					this.___createdAt = value;
					this.SendPropertyChanged("__createdAt");
					this.On__createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__updatedAt]", Storage="___updatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> @__updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				if ((this.___updatedAt != value))
				{
					this.On__updatedAtChanging(value);
					this.SendPropertyChanging();
					this.___updatedAt = value;
					this.SendPropertyChanged("__updatedAt");
					this.On__updatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__version]", Storage="___version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary @__version
		{
			get
			{
				return this.___version;
			}
			set
			{
				if ((this.___version != value))
				{
					this.On__versionChanging(value);
					this.SendPropertyChanging();
					this.___version = value;
					this.SendPropertyChanged("__version");
					this.On__versionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.BookingItem")]
	public partial class BookingItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTimeOffset ___createdAt;
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		
		private System.Data.Linq.Binary ___version;
		
		private string _Day;
		
		private string _droplocation;
		
		private string _Month;
		
		private string _npassengers;
		
		private string _pickuplocation;
		
		private string _username;
		
		private string _Year;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void On__createdAtChanging(System.DateTimeOffset value);
    partial void On__createdAtChanged();
    partial void On__updatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void On__updatedAtChanged();
    partial void On__versionChanging(System.Data.Linq.Binary value);
    partial void On__versionChanged();
    partial void OnDayChanging(string value);
    partial void OnDayChanged();
    partial void OndroplocationChanging(string value);
    partial void OndroplocationChanged();
    partial void OnMonthChanging(string value);
    partial void OnMonthChanged();
    partial void OnnpassengersChanging(string value);
    partial void OnnpassengersChanged();
    partial void OnpickuplocationChanging(string value);
    partial void OnpickuplocationChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    #endregion
		
		public BookingItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__createdAt]", Storage="___createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset @__createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				if ((this.___createdAt != value))
				{
					this.On__createdAtChanging(value);
					this.SendPropertyChanging();
					this.___createdAt = value;
					this.SendPropertyChanged("__createdAt");
					this.On__createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__updatedAt]", Storage="___updatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> @__updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				if ((this.___updatedAt != value))
				{
					this.On__updatedAtChanging(value);
					this.SendPropertyChanging();
					this.___updatedAt = value;
					this.SendPropertyChanged("__updatedAt");
					this.On__updatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__version]", Storage="___version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary @__version
		{
			get
			{
				return this.___version;
			}
			set
			{
				if ((this.___version != value))
				{
					this.On__versionChanging(value);
					this.SendPropertyChanging();
					this.___version = value;
					this.SendPropertyChanged("__version");
					this.On__versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_droplocation", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string droplocation
		{
			get
			{
				return this._droplocation;
			}
			set
			{
				if ((this._droplocation != value))
				{
					this.OndroplocationChanging(value);
					this.SendPropertyChanging();
					this._droplocation = value;
					this.SendPropertyChanged("droplocation");
					this.OndroplocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_npassengers", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string npassengers
		{
			get
			{
				return this._npassengers;
			}
			set
			{
				if ((this._npassengers != value))
				{
					this.OnnpassengersChanging(value);
					this.SendPropertyChanging();
					this._npassengers = value;
					this.SendPropertyChanged("npassengers");
					this.OnnpassengersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pickuplocation", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string pickuplocation
		{
			get
			{
				return this._pickuplocation;
			}
			set
			{
				if ((this._pickuplocation != value))
				{
					this.OnpickuplocationChanging(value);
					this.SendPropertyChanging();
					this._pickuplocation = value;
					this.SendPropertyChanged("pickuplocation");
					this.OnpickuplocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.CommandItem")]
	public partial class CommandItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTimeOffset ___createdAt;
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		
		private System.Data.Linq.Binary ___version;
		
		private string _command;
		
		private string _password;
		
		private string _username;
		
		private string _workgoup;
		
		private string _workgoup_state;
		
		private string _auth_level;
		
		private string _firstname;
		
		private string _lastname;
		
		private string _computername;
		
		private string _terminateprocess;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void On__createdAtChanging(System.DateTimeOffset value);
    partial void On__createdAtChanged();
    partial void On__updatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void On__updatedAtChanged();
    partial void On__versionChanging(System.Data.Linq.Binary value);
    partial void On__versionChanged();
    partial void OncommandChanging(string value);
    partial void OncommandChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnworkgoupChanging(string value);
    partial void OnworkgoupChanged();
    partial void Onworkgoup_stateChanging(string value);
    partial void Onworkgoup_stateChanged();
    partial void Onauth_levelChanging(string value);
    partial void Onauth_levelChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OncomputernameChanging(string value);
    partial void OncomputernameChanged();
    partial void OnterminateprocessChanging(string value);
    partial void OnterminateprocessChanged();
    #endregion
		
		public CommandItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__createdAt]", Storage="___createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset @__createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				if ((this.___createdAt != value))
				{
					this.On__createdAtChanging(value);
					this.SendPropertyChanging();
					this.___createdAt = value;
					this.SendPropertyChanged("__createdAt");
					this.On__createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__updatedAt]", Storage="___updatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> @__updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				if ((this.___updatedAt != value))
				{
					this.On__updatedAtChanging(value);
					this.SendPropertyChanging();
					this.___updatedAt = value;
					this.SendPropertyChanged("__updatedAt");
					this.On__updatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__version]", Storage="___version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary @__version
		{
			get
			{
				return this.___version;
			}
			set
			{
				if ((this.___version != value))
				{
					this.On__versionChanging(value);
					this.SendPropertyChanging();
					this.___version = value;
					this.SendPropertyChanged("__version");
					this.On__versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_command", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string command
		{
			get
			{
				return this._command;
			}
			set
			{
				if ((this._command != value))
				{
					this.OncommandChanging(value);
					this.SendPropertyChanging();
					this._command = value;
					this.SendPropertyChanged("command");
					this.OncommandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workgoup", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string workgoup
		{
			get
			{
				return this._workgoup;
			}
			set
			{
				if ((this._workgoup != value))
				{
					this.OnworkgoupChanging(value);
					this.SendPropertyChanging();
					this._workgoup = value;
					this.SendPropertyChanged("workgoup");
					this.OnworkgoupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workgoup_state", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string workgoup_state
		{
			get
			{
				return this._workgoup_state;
			}
			set
			{
				if ((this._workgoup_state != value))
				{
					this.Onworkgoup_stateChanging(value);
					this.SendPropertyChanging();
					this._workgoup_state = value;
					this.SendPropertyChanged("workgoup_state");
					this.Onworkgoup_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auth_level", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string auth_level
		{
			get
			{
				return this._auth_level;
			}
			set
			{
				if ((this._auth_level != value))
				{
					this.Onauth_levelChanging(value);
					this.SendPropertyChanging();
					this._auth_level = value;
					this.SendPropertyChanged("auth_level");
					this.Onauth_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_computername", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string computername
		{
			get
			{
				return this._computername;
			}
			set
			{
				if ((this._computername != value))
				{
					this.OncomputernameChanging(value);
					this.SendPropertyChanging();
					this._computername = value;
					this.SendPropertyChanged("computername");
					this.OncomputernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terminateprocess", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string terminateprocess
		{
			get
			{
				return this._terminateprocess;
			}
			set
			{
				if ((this._terminateprocess != value))
				{
					this.OnterminateprocessChanging(value);
					this.SendPropertyChanging();
					this._terminateprocess = value;
					this.SendPropertyChanged("terminateprocess");
					this.OnterminateprocessChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.Registration")]
	public partial class Registration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTimeOffset ___createdAt;
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		
		private System.Data.Linq.Binary ___version;
		
		private string _registrationId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void On__createdAtChanging(System.DateTimeOffset value);
    partial void On__createdAtChanged();
    partial void On__updatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void On__updatedAtChanged();
    partial void On__versionChanging(System.Data.Linq.Binary value);
    partial void On__versionChanged();
    partial void OnregistrationIdChanging(string value);
    partial void OnregistrationIdChanged();
    #endregion
		
		public Registration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__createdAt]", Storage="___createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset @__createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				if ((this.___createdAt != value))
				{
					this.On__createdAtChanging(value);
					this.SendPropertyChanging();
					this.___createdAt = value;
					this.SendPropertyChanged("__createdAt");
					this.On__createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__updatedAt]", Storage="___updatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> @__updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				if ((this.___updatedAt != value))
				{
					this.On__updatedAtChanging(value);
					this.SendPropertyChanging();
					this.___updatedAt = value;
					this.SendPropertyChanged("__updatedAt");
					this.On__updatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__version]", Storage="___version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary @__version
		{
			get
			{
				return this.___version;
			}
			set
			{
				if ((this.___version != value))
				{
					this.On__versionChanging(value);
					this.SendPropertyChanging();
					this.___version = value;
					this.SendPropertyChanged("__version");
					this.On__versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationId", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string registrationId
		{
			get
			{
				return this._registrationId;
			}
			set
			{
				if ((this._registrationId != value))
				{
					this.OnregistrationIdChanging(value);
					this.SendPropertyChanging();
					this._registrationId = value;
					this.SendPropertyChanged("registrationId");
					this.OnregistrationIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.ShuttleServices")]
	public partial class ShuttleService : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTimeOffset ___createdAt;
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		
		private System.Data.Linq.Binary ___version;
		
		private string _companyName;
		
		private string _driverImage;
		
		private string _driverName;
		
		private string _rating;
		
		private string _seatNumber;
		
		private string _tripPrice;
		
		private string _vehicleName;
		
		private string _vehicleImage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void On__createdAtChanging(System.DateTimeOffset value);
    partial void On__createdAtChanged();
    partial void On__updatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void On__updatedAtChanged();
    partial void On__versionChanging(System.Data.Linq.Binary value);
    partial void On__versionChanged();
    partial void OncompanyNameChanging(string value);
    partial void OncompanyNameChanged();
    partial void OndriverImageChanging(string value);
    partial void OndriverImageChanged();
    partial void OndriverNameChanging(string value);
    partial void OndriverNameChanged();
    partial void OnratingChanging(string value);
    partial void OnratingChanged();
    partial void OnseatNumberChanging(string value);
    partial void OnseatNumberChanged();
    partial void OntripPriceChanging(string value);
    partial void OntripPriceChanged();
    partial void OnvehicleNameChanging(string value);
    partial void OnvehicleNameChanged();
    partial void OnvehicleImageChanging(string value);
    partial void OnvehicleImageChanged();
    #endregion
		
		public ShuttleService()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__createdAt]", Storage="___createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset @__createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				if ((this.___createdAt != value))
				{
					this.On__createdAtChanging(value);
					this.SendPropertyChanging();
					this.___createdAt = value;
					this.SendPropertyChanged("__createdAt");
					this.On__createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__updatedAt]", Storage="___updatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> @__updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				if ((this.___updatedAt != value))
				{
					this.On__updatedAtChanging(value);
					this.SendPropertyChanging();
					this.___updatedAt = value;
					this.SendPropertyChanged("__updatedAt");
					this.On__updatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__version]", Storage="___version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary @__version
		{
			get
			{
				return this.___version;
			}
			set
			{
				if ((this.___version != value))
				{
					this.On__versionChanging(value);
					this.SendPropertyChanging();
					this.___version = value;
					this.SendPropertyChanged("__version");
					this.On__versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyName", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string companyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				if ((this._companyName != value))
				{
					this.OncompanyNameChanging(value);
					this.SendPropertyChanging();
					this._companyName = value;
					this.SendPropertyChanged("companyName");
					this.OncompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driverImage", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string driverImage
		{
			get
			{
				return this._driverImage;
			}
			set
			{
				if ((this._driverImage != value))
				{
					this.OndriverImageChanging(value);
					this.SendPropertyChanging();
					this._driverImage = value;
					this.SendPropertyChanged("driverImage");
					this.OndriverImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driverName", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string driverName
		{
			get
			{
				return this._driverName;
			}
			set
			{
				if ((this._driverName != value))
				{
					this.OndriverNameChanging(value);
					this.SendPropertyChanging();
					this._driverName = value;
					this.SendPropertyChanged("driverName");
					this.OndriverNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rating", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string rating
		{
			get
			{
				return this._rating;
			}
			set
			{
				if ((this._rating != value))
				{
					this.OnratingChanging(value);
					this.SendPropertyChanging();
					this._rating = value;
					this.SendPropertyChanged("rating");
					this.OnratingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seatNumber", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string seatNumber
		{
			get
			{
				return this._seatNumber;
			}
			set
			{
				if ((this._seatNumber != value))
				{
					this.OnseatNumberChanging(value);
					this.SendPropertyChanging();
					this._seatNumber = value;
					this.SendPropertyChanged("seatNumber");
					this.OnseatNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tripPrice", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string tripPrice
		{
			get
			{
				return this._tripPrice;
			}
			set
			{
				if ((this._tripPrice != value))
				{
					this.OntripPriceChanging(value);
					this.SendPropertyChanging();
					this._tripPrice = value;
					this.SendPropertyChanged("tripPrice");
					this.OntripPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleName", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string vehicleName
		{
			get
			{
				return this._vehicleName;
			}
			set
			{
				if ((this._vehicleName != value))
				{
					this.OnvehicleNameChanging(value);
					this.SendPropertyChanging();
					this._vehicleName = value;
					this.SendPropertyChanged("vehicleName");
					this.OnvehicleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicleImage", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string vehicleImage
		{
			get
			{
				return this._vehicleImage;
			}
			set
			{
				if ((this._vehicleImage != value))
				{
					this.OnvehicleImageChanging(value);
					this.SendPropertyChanging();
					this._vehicleImage = value;
					this.SendPropertyChanged("vehicleImage");
					this.OnvehicleImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.TodoItem")]
	public partial class TodoItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTimeOffset ___createdAt;
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		
		private System.Data.Linq.Binary ___version;
		
		private string _text;
		
		private System.Nullable<bool> _complete;
		
		private string _handle;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void On__createdAtChanging(System.DateTimeOffset value);
    partial void On__createdAtChanged();
    partial void On__updatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void On__updatedAtChanged();
    partial void On__versionChanging(System.Data.Linq.Binary value);
    partial void On__versionChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OncompleteChanging(System.Nullable<bool> value);
    partial void OncompleteChanged();
    partial void OnhandleChanging(string value);
    partial void OnhandleChanged();
    #endregion
		
		public TodoItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__createdAt]", Storage="___createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset @__createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				if ((this.___createdAt != value))
				{
					this.On__createdAtChanging(value);
					this.SendPropertyChanging();
					this.___createdAt = value;
					this.SendPropertyChanged("__createdAt");
					this.On__createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__updatedAt]", Storage="___updatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> @__updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				if ((this.___updatedAt != value))
				{
					this.On__updatedAtChanging(value);
					this.SendPropertyChanging();
					this.___updatedAt = value;
					this.SendPropertyChanged("__updatedAt");
					this.On__updatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__version]", Storage="___version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary @__version
		{
			get
			{
				return this.___version;
			}
			set
			{
				if ((this.___version != value))
				{
					this.On__versionChanging(value);
					this.SendPropertyChanging();
					this.___version = value;
					this.SendPropertyChanged("__version");
					this.On__versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complete", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> complete
		{
			get
			{
				return this._complete;
			}
			set
			{
				if ((this._complete != value))
				{
					this.OncompleteChanging(value);
					this.SendPropertyChanging();
					this._complete = value;
					this.SendPropertyChanged("complete");
					this.OncompleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_handle", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string handle
		{
			get
			{
				return this._handle;
			}
			set
			{
				if ((this._handle != value))
				{
					this.OnhandleChanging(value);
					this.SendPropertyChanging();
					this._handle = value;
					this.SendPropertyChanged("handle");
					this.OnhandleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Command;
		
		private string _Username;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCommandChanging(string value);
    partial void OnCommandChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Command", DbType="NVarChar(50)")]
		public string Command
		{
			get
			{
				return this._Command;
			}
			set
			{
				if ((this._Command != value))
				{
					this.OnCommandChanging(value);
					this.SendPropertyChanging();
					this._Command = value;
					this.SendPropertyChanged("Command");
					this.OnCommandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="locationawarepm.UserRegistration")]
	public partial class UserRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private System.DateTimeOffset ___createdAt;
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		
		private System.Data.Linq.Binary ___version;
		
		private string _CardMM;
		
		private string _creditcardnumber;
		
		private string _CVV;
		
		private string _CardYY;
		
		private string _password;
		
		private string _username;
		
		private string _firstname;
		
		private string _lastname;
		
		private string _phonenumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void On__createdAtChanging(System.DateTimeOffset value);
    partial void On__createdAtChanged();
    partial void On__updatedAtChanging(System.Nullable<System.DateTimeOffset> value);
    partial void On__updatedAtChanged();
    partial void On__versionChanging(System.Data.Linq.Binary value);
    partial void On__versionChanged();
    partial void OnCardMMChanging(string value);
    partial void OnCardMMChanged();
    partial void OncreditcardnumberChanging(string value);
    partial void OncreditcardnumberChanged();
    partial void OnCVVChanging(string value);
    partial void OnCVVChanged();
    partial void OnCardYYChanging(string value);
    partial void OnCardYYChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnphonenumberChanging(string value);
    partial void OnphonenumberChanged();
    #endregion
		
		public UserRegistration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__createdAt]", Storage="___createdAt", DbType="DateTimeOffset NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTimeOffset @__createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				if ((this.___createdAt != value))
				{
					this.On__createdAtChanging(value);
					this.SendPropertyChanging();
					this.___createdAt = value;
					this.SendPropertyChanged("__createdAt");
					this.On__createdAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__updatedAt]", Storage="___updatedAt", DbType="DateTimeOffset", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTimeOffset> @__updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				if ((this.___updatedAt != value))
				{
					this.On__updatedAtChanging(value);
					this.SendPropertyChanging();
					this.___updatedAt = value;
					this.SendPropertyChanged("__updatedAt");
					this.On__updatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[__version]", Storage="___version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary @__version
		{
			get
			{
				return this.___version;
			}
			set
			{
				if ((this.___version != value))
				{
					this.On__versionChanging(value);
					this.SendPropertyChanging();
					this.___version = value;
					this.SendPropertyChanged("__version");
					this.On__versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardMM", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string CardMM
		{
			get
			{
				return this._CardMM;
			}
			set
			{
				if ((this._CardMM != value))
				{
					this.OnCardMMChanging(value);
					this.SendPropertyChanging();
					this._CardMM = value;
					this.SendPropertyChanged("CardMM");
					this.OnCardMMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creditcardnumber", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string creditcardnumber
		{
			get
			{
				return this._creditcardnumber;
			}
			set
			{
				if ((this._creditcardnumber != value))
				{
					this.OncreditcardnumberChanging(value);
					this.SendPropertyChanging();
					this._creditcardnumber = value;
					this.SendPropertyChanged("creditcardnumber");
					this.OncreditcardnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVV", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string CVV
		{
			get
			{
				return this._CVV;
			}
			set
			{
				if ((this._CVV != value))
				{
					this.OnCVVChanging(value);
					this.SendPropertyChanging();
					this._CVV = value;
					this.SendPropertyChanged("CVV");
					this.OnCVVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardYY", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string CardYY
		{
			get
			{
				return this._CardYY;
			}
			set
			{
				if ((this._CardYY != value))
				{
					this.OnCardYYChanging(value);
					this.SendPropertyChanging();
					this._CardYY = value;
					this.SendPropertyChanged("CardYY");
					this.OnCardYYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phonenumber", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string phonenumber
		{
			get
			{
				return this._phonenumber;
			}
			set
			{
				if ((this._phonenumber != value))
				{
					this.OnphonenumberChanging(value);
					this.SendPropertyChanging();
					this._phonenumber = value;
					this.SendPropertyChanged("phonenumber");
					this.OnphonenumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
	public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Command;
		
		private string _Username;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCommandChanging(string value);
    partial void OnCommandChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Command", DbType="NVarChar(50)")]
		public string Command
		{
			get
			{
				return this._Command;
			}
			set
			{
				if ((this._Command != value))
				{
					this.OnCommandChanging(value);
					this.SendPropertyChanging();
					this._Command = value;
					this.SendPropertyChanged("Command");
					this.OnCommandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
